In [ ]:
import pandas as pd
import numpy as np
import random as rd
import os

In [ ]:
fruits= {"apple":[0,6,7,8,12,11],"banana":[0,2,6,12,3,1],"kiwi":[0,8,4,2,1,13]}
m_fruits =pd.DataFrame(fruits)

In [ ]:
m_fruits

   apple  banana  kiwi
0      0       0     0
1      6       2     8
2      7       6     4
3      8      12     2
4     12       3     1
5     11       1    13

In [ ]:
dairyproducts = {"bread":[2,5,6,9,12,15],"butter":[0,2,7,4,10,17],"cheese":[0,5,4,8,9,14]}
m_dairyproducts=pd.DataFrame(dairyproducts)

In [ ]:
m_dairyproducts

   bread  butter  cheese
0      2       0       0
1      5       2       5
2      6       7       4
3      9       4       8
4     12      10       9
5     15      17      14

In [ ]:
chocolate={"dairymilk":[0,5,6,7,1,12],"fivestar":[0,5,6,4,1,15],"kindercreamy":[0,3,6,8,3,11]}
m_chocolate=pd.DataFrame(chocolate)

In [ ]:
m_chocolate

   dairymilk  fivestar  kindercreamy
0          0         0             0
1          5         5             3
2          6         6             6
3          7         4             8
4          1         1             3
5         12        15            11

In [ ]:
toys={"car":[0,1,3,4,5,6],"teddy":[0,2,3,4,5,6],"talkingtom":[0,2,3,4,5,6]}
m_toys=pd.DataFrame(toys)

In [ ]:
m_toys

   car  teddy  talkingtom
0    0      0           0
1    1      2           2
2    3      3           3
3    4      4           4
4    5      5           5
5    6      6           6

In [ ]:
vegetables={"tomato":[0,4,5,7,8,6],"onion":[0,5,6,7,1,9],"carrot":[0,4,5,7,8,9]}
m_vegetables=pd.DataFrame(vegetables)

In [ ]:
m_vegetables

   tomato  onion  carrot
0       0      0       0
1       4      5       4
2       5      6       5
3       7      7       7
4       8      1       8
5       6      9       9

In [ ]:
def gen_basket(no_of_recs):

    t_apple = rd.choices(m_fruits.apple,k=no_of_recs)
    t_kiwi = rd.choices(m_fruits.kiwi,k=no_of_recs)
    t_bread = rd.choices(m_dairyproducts.bread,k=no_of_recs)
    t_cheese = rd.choices(m_dairyproducts.cheese,k=no_of_recs)
    t_dairymilk=rd.choices(m_chocolate.dairymilk,k=no_of_recs)
    t_kindercreamy=rd.choices(m_chocolate.kindercreamy,k=no_of_recs)
    t_teddy=rd.choices(m_toys.teddy,k=no_of_recs)
    t_talkingtom=rd.choices(m_toys.talkingtom,k=no_of_recs)
    t_tomato=rd.choices(m_vegetables.tomato,k=no_of_recs)
    t_onion=rd.choices(m_vegetables.onion,k=no_of_recs)
    cube = pd.DataFrame({'apple':t_apple,
                      'kiwi':t_kiwi,
                         'bread':t_bread,
                         'cheese':t_cheese,
                         'dairymilk':t_dairymilk,
                         'kindercreamy':t_kindercreamy,
                         'teddy':t_teddy,
                         'talkingtom':t_talkingtom,
                         'tomato':t_tomato,
                         'onion':t_onion,
                         }
                      )
    return(cube)

In [ ]:
test =gen_basket(50)

In [ ]:
test

,apple,kiwi,bread,cheese,dairymilk,kindercreamy,teddy,talkingtom,tomato,onion
0,0,0,5,4,5,3,0,4,8,1
1,7,13,5,14,0,6,4,2,5,5
2,6,13,9,8,6,0,6,0,7,5
3,7,1,5,4,5,0,5,3,0,0
4,8,13,6,0,6,6,5,4,8,1
5,8,1,9,9,7,6,6,6,6,7
6,0,1,15,5,0,3,5,5,7,1
7,12,1,2,5,0,11,4,2,5,6
8,7,0,2,8,0,6,4,5,5,0
9,8,2,15,14,7,8,5,2,0,5
10,0,4,12,14,0,8,4,0,5,6
11,0,8,2,0,5,3,0,3,5,5
12,6,2,5,5,12,11,2,3,7,7
13,8,0,15,5,6,0,4,6,0,1
14,0,0,5,5,5,3,2,6,5,5
15,12,2,6,5,6,0,4,5,4,5
16,11,4,9,4,0,3,3,5,0,7
17,7,13,6,5,5,8,4,3,6,6
18,0,4,12,4,6,6,0,0,5,0
19,11,1,6,8,7,6,4,0,5,7
20,12,8,6,5,12,8,6,3,0,6
21,11,4,15,14,12,3,2,3,6,1
22,12,2,9,4,7,8,4,0,7,5
23,6,2,15,4,6,11,5,2,6,5
24,8,1,5,5,5,6,3,2,4,7
25,0,4,9,8,5,3,5,3,6,6
26,8,2,6,14,7,8,4,3,5,5
27,6,8,9,9,5,8,2,3,5,1
28,8,4,6,14,1,3,5,0,0,0
29,7,2,9,8,7,11,4,3,6,5
30,6,2,5,0,1,3,2,2,5,9
31,8,0,9,4,1,8,5,5,4,9
32,11,0,12,8,6,3,6,3,0,6
33,0,8,2,8,6,3,2,4,4,6
34,7,4,15,8,1,8,4,4,5,6
35,8,2,9,5,7,3,6,3,7,6
36,0,8,9,5,5,0,5,6,0,6
37,6,2,2,9,6,8,5,3,8,7
38,11,2,2,0,12,11,2,0,0,5
39,6,8,12,9,7,0,6,0,5,1
40,6,13,2,4,7,6,6,2,4,6
41,12,1,5,4,6,3,0,3,8,9
42,7,2,5,9,7,6,2,2,0,1
43,0,1,12,8,1,11,6,6,4,5
44,11,2,5,4,6,3,5,3,0,0
45,0,4,2,14,7,11,4,3,5,0
46,12,0,2,5,0,3,2,0,6,0
47,7,8,12,8,5,3,5,5,4,5
48,12,4,15,5,12,3,0,3,0,7
49,12,13,6,9,5,6,4,3,5,5

In [ ]:
test["value"] = 1

In [ ]:
test

,apple,kiwi,bread,cheese,dairymilk,kindercreamy,teddy,talkingtom,tomato,onion,value
0,0,0,5,4,5,3,0,4,8,1,1
1,7,13,5,14,0,6,4,2,5,5,1
2,6,13,9,8,6,0,6,0,7,5,1
3,7,1,5,4,5,0,5,3,0,0,1
4,8,13,6,0,6,6,5,4,8,1,1
5,8,1,9,9,7,6,6,6,6,7,1
6,0,1,15,5,0,3,5,5,7,1,1
7,12,1,2,5,0,11,4,2,5,6,1
8,7,0,2,8,0,6,4,5,5,0,1
9,8,2,15,14,7,8,5,2,0,5,1
10,0,4,12,14,0,8,4,0,5,6,1
11,0,8,2,0,5,3,0,3,5,5,1
12,6,2,5,5,12,11,2,3,7,7,1
13,8,0,15,5,6,0,4,6,0,1,1
14,0,0,5,5,5,3,2,6,5,5,1
15,12,2,6,5,6,0,4,5,4,5,1
16,11,4,9,4,0,3,3,5,0,7,1
17,7,13,6,5,5,8,4,3,6,6,1
18,0,4,12,4,6,6,0,0,5,0,1
19,11,1,6,8,7,6,4,0,5,7,1
20,12,8,6,5,12,8,6,3,0,6,1
21,11,4,15,14,12,3,2,3,6,1,1
22,12,2,9,4,7,8,4,0,7,5,1
23,6,2,15,4,6,11,5,2,6,5,1
24,8,1,5,5,5,6,3,2,4,7,1
25,0,4,9,8,5,3,5,3,6,6,1
26,8,2,6,14,7,8,4,3,5,5,1
27,6,8,9,9,5,8,2,3,5,1,1
28,8,4,6,14,1,3,5,0,0,0,1
29,7,2,9,8,7,11,4,3,6,5,1
30,6,2,5,0,1,3,2,2,5,9,1
31,8,0,9,4,1,8,5,5,4,9,1
32,11,0,12,8,6,3,6,3,0,6,1
33,0,8,2,8,6,3,2,4,4,6,1
34,7,4,15,8,1,8,4,4,5,6,1
35,8,2,9,5,7,3,6,3,7,6,1
36,0,8,9,5,5,0,5,6,0,6,1
37,6,2,2,9,6,8,5,3,8,7,1
38,11,2,2,0,12,11,2,0,0,5,1
39,6,8,12,9,7,0,6,0,5,1,1
40,6,13,2,4,7,6,6,2,4,6,1
41,12,1,5,4,6,3,0,3,8,9,1
42,7,2,5,9,7,6,2,2,0,1,1
43,0,1,12,8,1,11,6,6,4,5,1
44,11,2,5,4,6,3,5,3,0,0,1
45,0,4,2,14,7,11,4,3,5,0,1
46,12,0,2,5,0,3,2,0,6,0,1
47,7,8,12,8,5,3,5,5,4,5,1
48,12,4,15,5,12,3,0,3,0,7,1
49,12,13,6,9,5,6,4,3,5,5,1

In [ ]:
def amount(cols):
    value = cols[0]
    a = cols[1]
    b =cols[2]
    c =cols[3]
    d =cols[4]
    e =cols[5]
    f =cols[6]
    g =cols[7]
    h =cols[8]
    i =cols[9]
    j =cols[10]
    while value == 1:
     amountt=a*25+b*30+c*5+d*20+e*10+f*30+g*150+h*200+i*6+j*4
     return amountt

In [ ]:
test["amount"] = test[['value','apple','kiwi','bread','cheese','dairymilk','kindercreamy','teddy','talkingtom','tomato','onion']].apply(amount,axis=1)

In [ ]:
test

,apple,kiwi,bread,cheese,dairymilk,kindercreamy,teddy,talkingtom,tomato,onion,value,amount
0,0,0,5,4,5,3,0,4,8,1,1,1097
1,7,13,5,14,0,6,4,2,5,5,1,2100
2,6,13,9,8,6,0,6,0,7,5,1,1767
3,7,1,5,4,5,0,5,3,0,0,1,1710
4,8,13,6,0,6,6,5,4,8,1,1,2462
5,8,1,9,9,7,6,6,6,6,7,1,2869
6,0,1,15,5,0,3,5,5,7,1,1,2091
7,12,1,2,5,0,11,4,2,5,6,1,1824
8,7,0,2,8,0,6,4,5,5,0,1,2155
9,8,2,15,14,7,8,5,2,0,5,1,2095
10,0,4,12,14,0,8,4,0,5,6,1,1354
11,0,8,2,0,5,3,0,3,5,5,1,1040
12,6,2,5,5,12,11,2,3,7,7,1,1755
13,8,0,15,5,6,0,4,6,0,1,1,2239
14,0,0,5,5,5,3,2,6,5,5,1,1815
15,12,2,6,5,6,0,4,5,4,5,1,2194
16,11,4,9,4,0,3,3,5,0,7,1,2088
17,7,13,6,5,5,8,4,3,6,6,1,2245
18,0,4,12,4,6,6,0,0,5,0,1,530
19,11,1,6,8,7,6,4,0,5,7,1,1403
20,12,8,6,5,12,8,6,3,0,6,1,2554
21,11,4,15,14,12,3,2,3,6,1,1,1900
22,12,2,9,4,7,8,4,0,7,5,1,1457
23,6,2,15,4,6,11,5,2,6,5,1,1961
24,8,1,5,5,5,6,3,2,4,7,1,1487
25,0,4,9,8,5,3,5,3,6,6,1,1875
26,8,2,6,14,7,8,4,3,5,5,1,2130
27,6,8,9,9,5,8,2,3,5,1,1,1839
28,8,4,6,14,1,3,5,0,0,0,1,1480
29,7,2,9,8,7,11,4,3,6,5,1,2096
30,6,2,5,0,1,3,2,2,5,9,1,1101
31,8,0,9,4,1,8,5,5,4,9,1,2385
32,11,0,12,8,6,3,6,3,0,6,1,2169
33,0,8,2,8,6,3,2,4,4,6,1,1708
34,7,4,15,8,1,8,4,4,5,6,1,2234
35,8,2,9,5,7,3,6,3,7,6,1,2131
36,0,8,9,5,5,0,5,6,0,6,1,2409
37,6,2,2,9,6,8,5,3,8,7,1,2126
38,11,2,2,0,12,11,2,0,0,5,1,1115
39,6,8,12,9,7,0,6,0,5,1,1,1634
40,6,13,2,4,7,6,6,2,4,6,1,2228
41,12,1,5,4,6,3,0,3,8,9,1,1269
42,7,2,5,9,7,6,2,2,0,1,1,1394
43,0,1,12,8,1,11,6,6,4,5,1,2734
44,11,2,5,4,6,3,5,3,0,0,1,1940
45,0,4,2,14,7,11,4,3,5,0,1,2040
46,12,0,2,5,0,3,2,0,6,0,1,836
47,7,8,12,8,5,3,5,5,4,5,1,2569
48,12,4,15,5,12,3,0,3,0,7,1,1433
49,12,13,6,9,5,6,4,3,5,5,1,2380

In [ ]:
test.to_csv('cube.csv')
cubee = os.path.abspath("cube.csv")
dw =  pd.read_csv(cubee)
dw

,Unnamed: 0,apple,kiwi,bread,cheese,dairymilk,kindercreamy,teddy,talkingtom,tomato,onion,value,amount
0,0,0,0,5,4,5,3,0,4,8,1,1,1097
1,1,7,13,5,14,0,6,4,2,5,5,1,2100
2,2,6,13,9,8,6,0,6,0,7,5,1,1767
3,3,7,1,5,4,5,0,5,3,0,0,1,1710
4,4,8,13,6,0,6,6,5,4,8,1,1,2462
5,5,8,1,9,9,7,6,6,6,6,7,1,2869
6,6,0,1,15,5,0,3,5,5,7,1,1,2091
7,7,12,1,2,5,0,11,4,2,5,6,1,1824
8,8,7,0,2,8,0,6,4,5,5,0,1,2155
9,9,8,2,15,14,7,8,5,2,0,5,1,2095
10,10,0,4,12,14,0,8,4,0,5,6,1,1354
11,11,0,8,2,0,5,3,0,3,5,5,1,1040
12,12,6,2,5,5,12,11,2,3,7,7,1,1755
13,13,8,0,15,5,6,0,4,6,0,1,1,2239
14,14,0,0,5,5,5,3,2,6,5,5,1,1815
15,15,12,2,6,5,6,0,4,5,4,5,1,2194
16,16,11,4,9,4,0,3,3,5,0,7,1,2088
17,17,7,13,6,5,5,8,4,3,6,6,1,2245
18,18,0,4,12,4,6,6,0,0,5,0,1,530
19,19,11,1,6,8,7,6,4,0,5,7,1,1403
20,20,12,8,6,5,12,8,6,3,0,6,1,2554
21,21,11,4,15,14,12,3,2,3,6,1,1,1900
22,22,12,2,9,4,7,8,4,0,7,5,1,1457
23,23,6,2,15,4,6,11,5,2,6,5,1,1961
24,24,8,1,5,5,5,6,3,2,4,7,1,1487
25,25,0,4,9,8,5,3,5,3,6,6,1,1875
26,26,8,2,6,14,7,8,4,3,5,5,1,2130
27,27,6,8,9,9,5,8,2,3,5,1,1,1839
28,28,8,4,6,14,1,3,5,0,0,0,1,1480
29,29,7,2,9,8,7,11,4,3,6,5,1,2096
30,30,6,2,5,0,1,3,2,2,5,9,1,1101
31,31,8,0,9,4,1,8,5,5,4,9,1,2385
32,32,11,0,12,8,6,3,6,3,0,6,1,2169
33,33,0,8,2,8,6,3,2,4,4,6,1,1708
34,34,7,4,15,8,1,8,4,4,5,6,1,2234
35,35,8,2,9,5,7,3,6,3,7,6,1,2131
36,36,0,8,9,5,5,0,5,6,0,6,1,2409
37,37,6,2,2,9,6,8,5,3,8,7,1,2126
38,38,11,2,2,0,12,11,2,0,0,5,1,1115
39,39,6,8,12,9,7,0,6,0,5,1,1,1634
40,40,6,13,2,4,7,6,6,2,4,6,1,2228
41,41,12,1,5,4,6,3,0,3,8,9,1,1269
42,42,7,2,5,9,7,6,2,2,0,1,1,1394
43,43,0,1,12,8,1,11,6,6,4,5,1,2734
44,44,11,2,5,4,6,3,5,3,0,0,1,1940
45,45,0,4,2,14,7,11,4,3,5,0,1,2040
46,46,12,0,2,5,0,3,2,0,6,0,1,836
47,47,7,8,12,8,5,3,5,5,4,5,1,2569
48,48,12,4,15,5,12,3,0,3,0,7,1,1433
49,49,12,13,6,9,5,6,4,3,5,5,1,2380

In [ ]:
dw.drop(['Unnamed: 0','value'],axis=1,inplace=True)

In [ ]:
dw

,apple,kiwi,bread,cheese,dairymilk,kindercreamy,teddy,talkingtom,tomato,onion,amount
0,0,0,5,4,5,3,0,4,8,1,1097
1,7,13,5,14,0,6,4,2,5,5,2100
2,6,13,9,8,6,0,6,0,7,5,1767
3,7,1,5,4,5,0,5,3,0,0,1710
4,8,13,6,0,6,6,5,4,8,1,2462
5,8,1,9,9,7,6,6,6,6,7,2869
6,0,1,15,5,0,3,5,5,7,1,2091
7,12,1,2,5,0,11,4,2,5,6,1824
8,7,0,2,8,0,6,4,5,5,0,2155
9,8,2,15,14,7,8,5,2,0,5,2095
10,0,4,12,14,0,8,4,0,5,6,1354
11,0,8,2,0,5,3,0,3,5,5,1040
12,6,2,5,5,12,11,2,3,7,7,1755
13,8,0,15,5,6,0,4,6,0,1,2239
14,0,0,5,5,5,3,2,6,5,5,1815
15,12,2,6,5,6,0,4,5,4,5,2194
16,11,4,9,4,0,3,3,5,0,7,2088
17,7,13,6,5,5,8,4,3,6,6,2245
18,0,4,12,4,6,6,0,0,5,0,530
19,11,1,6,8,7,6,4,0,5,7,1403
20,12,8,6,5,12,8,6,3,0,6,2554
21,11,4,15,14,12,3,2,3,6,1,1900
22,12,2,9,4,7,8,4,0,7,5,1457
23,6,2,15,4,6,11,5,2,6,5,1961
24,8,1,5,5,5,6,3,2,4,7,1487
25,0,4,9,8,5,3,5,3,6,6,1875
26,8,2,6,14,7,8,4,3,5,5,2130
27,6,8,9,9,5,8,2,3,5,1,1839
28,8,4,6,14,1,3,5,0,0,0,1480
29,7,2,9,8,7,11,4,3,6,5,2096
30,6,2,5,0,1,3,2,2,5,9,1101
31,8,0,9,4,1,8,5,5,4,9,2385
32,11,0,12,8,6,3,6,3,0,6,2169
33,0,8,2,8,6,3,2,4,4,6,1708
34,7,4,15,8,1,8,4,4,5,6,2234
35,8,2,9,5,7,3,6,3,7,6,2131
36,0,8,9,5,5,0,5,6,0,6,2409
37,6,2,2,9,6,8,5,3,8,7,2126
38,11,2,2,0,12,11,2,0,0,5,1115
39,6,8,12,9,7,0,6,0,5,1,1634
40,6,13,2,4,7,6,6,2,4,6,2228
41,12,1,5,4,6,3,0,3,8,9,1269
42,7,2,5,9,7,6,2,2,0,1,1394
43,0,1,12,8,1,11,6,6,4,5,2734
44,11,2,5,4,6,3,5,3,0,0,1940
45,0,4,2,14,7,11,4,3,5,0,2040
46,12,0,2,5,0,3,2,0,6,0,836
47,7,8,12,8,5,3,5,5,4,5,2569
48,12,4,15,5,12,3,0,3,0,7,1433
49,12,13,6,9,5,6,4,3,5,5,2380

In [ ]:
dc = dw[( (dw['apple'] ==12) | (dw['apple'] ==8) | (dw['apple'] ==5)) & ( (dw['teddy'] ==4) | (dw['teddy'] ==3) | (dw['teddy'] ==1)) &
             ((dw['kindercreamy'] == 3) | (dw['kindercreamy'] == 8) | (dw['kindercreamy'] == 11) ) &
        ((dw['cheese'] == 2) | (dw['cheese'] == 4) | (dw['cheese'] == 5))]
dc.groupby(['apple','kiwi','bread','cheese','dairymilk','kindercreamy','teddy','talkingtom','tomato','onion']).sum()

                                                                              amount
apple kiwi bread cheese dairymilk kindercreamy teddy talkingtom tomato onion
12    1    2     5      0         11           4     2          5      6        1824
      2    9     4      7         8            4     0          7      5        1457

In [ ]:
dw.pivot_table(index='tomato',columns='onion',values='amount')

onion        0       1       5            6       7       9
tomato
0       1710.0  1816.5  1605.0  2377.333333  1760.5     NaN
4          NaN     NaN  2499.0  1968.000000  1487.0  2385.0
5       1575.0  1736.5  1893.0  1804.000000  1403.0  1101.0
6        836.0  1900.0  2028.5  2060.000000  2869.0     NaN
7          NaN  2091.0  1612.0  2131.000000  1755.0     NaN
8          NaN  1779.5     NaN          NaN  2126.0  1269.0

In [ ]:
sum = dw[(dw['apple'] == 11) & (dw['teddy'] == 2) & (dw['kindercreamy'] == 0) & (dw['cheese'] == 4)]

In [ ]:
sum

Empty DataFrame
Columns: [apple, kiwi, bread, cheese, dairymilk, kindercreamy, teddy, talkingtom, tomato, onion, amount]
Index: []

In [ ]:
roll = dw.groupby(['bread', 'cheese', 'dairymilk', 'kindercreamy', 'teddy', 'talkingtom', 'tomato', 'onion']).sum()

In [ ]:
roll

                                                                   apple  \
bread cheese dairymilk kindercreamy teddy talkingtom tomato onion
2     0      5         3            0     3          5      5          0
             12        11           2     0          0      5         11
      4      7         6            6     2          4      6          6
      5      0         3            2     0          6      0         12
                       11           4     2          5      6         12
      8      0         6            4     5          5      0          7
             6         3            2     4          4      6          0
      9      6         8            5     3          8      7          6
      14     7         11           4     3          5      0          0
5     0      1         3            2     2          5      9          6
      4      5         0            5     3          0      0          7
                       3            0     4          8      1          0
             6         3            0     3          8      9         12
                                    5     3          0      0         11
      5      5         3            2     6          5      5          0
                       6            3     2          4      7          8
             12        11           2     3          7      7          6
      9      7         6            2     2          0      1          7
      14     0         6            4     2          5      5          7
6     0      6         6            5     4          8      1          8
      5      5         8            4     3          6      6          7
             6         0            4     5          4      5         12
             12        8            6     3          0      6         12
      8      7         6            4     0          5      7         11
      9      5         6            4     3          5      5         12
      14     1         3            5     0          0      0          8
             7         8            4     3          5      5          8
9     4      0         3            3     5          0      7         11
             1         8            5     5          4      9          8
             7         8            4     0          7      5         12
      5      5         0            5     6          0      6          0
             7         3            6     3          7      6          8
      8      5         3            5     3          6      6          0
             6         0            6     0          7      5          6
             7         11           4     3          6      5          7
      9      5         8            2     3          5      1          6
             7         6            6     6          6      7          8
12    4      6         6            0     0          5      0          0
      8      1         11           6     6          4      5          0
             5         3            5     5          4      5          7
             6         3            6     3          0      6         11
      9      7         0            6     0          5      1          6
      14     0         8            4     0          5      6          0
15    4      6         11           5     2          6      5          6
      5      0         3            5     5          7      1          0
             6         0            4     6          0      1          8
             12        3            0     3          0      7         12
      8      1         8            4     4          5      6          7
      14     7         8            5     2          0      5          8
             12        3            2     3          6      1         11

                                                                   kiwi  \
bread cheese dairymilk kindercreamy teddy talkingtom tomato onion
2     0      5         3            0     3          5      5         8
             12        11           2     0          0      5         2
      4      7         6            6     2          4      6        13
      5      0         3            2     0          6      0         0
                       11           4     2          5      6         1
      8      0         6            4     5          5      0         0
             6         3            2     4          4      6         8
      9      6         8            5     3          8      7         2
      14     7         11           4     3          5      0         4
5     0      1         3            2     2          5      9         2
      4      5         0            5     3          0      0         1
                       3            0     4          8      1         0
             6         3            0     3          8      9         1
                                    5     3          0      0         2
      5      5         3            2     6          5      5         0
                       6            3     2          4      7         1
             12        11           2     3          7      7         2
      9      7         6            2     2          0      1         2
      14     0         6            4     2          5      5        13
6     0      6         6            5     4          8      1        13
      5      5         8            4     3          6      6        13
             6         0            4     5          4      5         2
             12        8            6     3          0      6         8
      8      7         6            4     0          5      7         1
      9      5         6            4     3          5      5        13
      14     1         3            5     0          0      0         4
             7         8            4     3          5      5         2
9     4      0         3            3     5          0      7         4
             1         8            5     5          4      9         0
             7         8            4     0          7      5         2
      5      5         0            5     6          0      6         8
             7         3            6     3          7      6         2
      8      5         3            5     3          6      6         4
             6         0            6     0          7      5        13
             7         11           4     3          6      5         2
      9      5         8            2     3          5      1         8
             7         6            6     6          6      7         1
12    4      6         6            0     0          5      0         4
      8      1         11           6     6          4      5         1
             5         3            5     5          4      5         8
             6         3            6     3          0      6         0
      9      7         0            6     0          5      1         8
      14     0         8            4     0          5      6         4
15    4      6         11           5     2          6      5         2
      5      0         3            5     5          7      1         1
             6         0            4     6          0      1         0
             12        3            0     3          0      7         4
      8      1         8            4     4          5      6         4
      14     7         8            5     2          0      5         2
             12        3            2     3          6      1         4

                                                                   amount
bread cheese dairymilk kindercreamy teddy talkingtom tomato onion
2     0      5         3            0     3          5      5        1040
             12        11           2     0          0      5        1115
      4      7         6            6     2          4      6        2228
      5      0         3            2     0          6      0         836
                       11           4     2          5      6        1824
      8      0         6            4     5          5      0        2155
             6         3            2     4          4      6        1708
      9      6         8            5     3          8      7        2126
      14     7         11           4     3          5      0        2040
5     0      1         3            2     2          5      9        1101
      4      5         0            5     3          0      0        1710
                       3            0     4          8      1        1097
             6         3            0     3          8      9        1269
                                    5     3          0      0        1940
      5      5         3            2     6          5      5        1815
                       6            3     2          4      7        1487
             12        11           2     3          7      7        1755
      9      7         6            2     2          0      1        1394
      14     0         6            4     2          5      5        2100
6     0      6         6            5     4          8      1        2462
      5      5         8            4     3          6      6        2245
             6         0            4     5          4      5        2194
             12        8            6     3          0      6        2554
      8      7         6            4     0          5      7        1403
      9      5         6            4     3          5      5        2380
      14     1         3            5     0          0      0        1480
             7         8            4     3          5      5        2130
9     4      0         3            3     5          0      7        2088
             1         8            5     5          4      9        2385
             7         8            4     0          7      5        1457
      5      5         0            5     6          0      6        2409
             7         3            6     3          7      6        2131
      8      5         3            5     3          6      6        1875
             6         0            6     0          7      5        1767
             7         11           4     3          6      5        2096
      9      5         8            2     3          5      1        1839
             7         6            6     6          6      7        2869
12    4      6         6            0     0          5      0         530
      8      1         11           6     6          4      5        2734
             5         3            5     5          4      5        2569
             6         3            6     3          0      6        2169
      9      7         0            6     0          5      1        1634
      14     0         8            4     0          5      6        1354
15    4      6         11           5     2          6      5        1961
      5      0         3            5     5          7      1        2091
             6         0            4     6          0      1        2239
             12        3            0     3          0      7        1433
      8      1         8            4     4          5      6        2234
      14     7         8            5     2          0      5        2095
             12        3            2     3          6      1        1900

In [ ]:
drill = dw.groupby(['apple', 'kiwi', 'teddy', 'talkingtom']).sum()

In [ ]:
drill

                             bread  cheese  dairymilk  kindercreamy  tomato  \
apple kiwi teddy talkingtom
0     0    0     4               5       4          5             3       8
           2     6               5       5          5             3       5
      1    5     5              15       5          0             3       7
           6     6              12       8          1            11       4
      4    0     0              12       4          6             6       5
           4     0              12      14          0             8       5
                 3               2      14          7            11       5
           5     3               9       8          5             3       6
      8    0     3               2       0          5             3       5
           2     4               2       8          6             3       4
           5     6               9       5          5             0       0
6     2    2     2               5       0          1             3       5
                 3               5       5         12            11       7
           5     2              15       4          6            11       6
                 3               2       9          6             8       8
      8    2     3               9       9          5             8       5
           6     0              12       9          7             0       5
      13   6     0               9       8          6             0       7
                 2               2       4          7             6       4
7     0    4     5               2       8          0             6       5
      1    5     3               5       4          5             0       0
      2    2     2               5       9          7             6       0
           4     3               9       8          7            11       6
      4    4     4              15       8          1             8       5
      8    5     5              12       8          5             3       4
      13   4     2               5      14          0             6       5
                 3               6       5          5             8       6
8     0    4     6              15       5          6             0       0
           5     5               9       4          1             8       4
      1    3     2               5       5          5             6       4
           6     6               9       9          7             6       6
      2    4     3               6      14          7             8       5
           5     2              15      14          7             8       0
           6     3               9       5          7             3       7
      4    5     0               6      14          1             3       0
      13   5     4               6       0          6             6       8
11    0    6     3              12       8          6             3       0
      1    4     0               6       8          7             6       5
      2    2     0               2       0         12            11       0
           5     3               5       4          6             3       0
      4    2     3              15      14         12             3       6
           3     5               9       4          0             3       0
12    0    2     0               2       5          0             3       6
      1    0     3               5       4          6             3       8
           4     2               2       5          0            11       5
      2    4     0               9       4          7             8       7
                 5               6       5          6             0       4
      4    0     3              15       5         12             3       0
      8    6     3               6       5         12             8       0
      13   4     3               6       9          5             6       5

                             onion  amount
apple kiwi teddy talkingtom
0     0    0     4               1    1097
           2     6               5    1815
      1    5     5               1    2091
           6     6               5    2734
      4    0     0               0     530
           4     0               6    1354
                 3               0    2040
           5     3               6    1875
      8    0     3               5    1040
           2     4               6    1708
           5     6               6    2409
6     2    2     2               9    1101
                 3               7    1755
           5     2               5    1961
                 3               7    2126
      8    2     3               1    1839
           6     0               1    1634
      13   6     0               5    1767
                 2               6    2228
7     0    4     5               0    2155
      1    5     3               0    1710
      2    2     2               1    1394
           4     3               5    2096
      4    4     4               6    2234
      8    5     5               5    2569
      13   4     2               5    2100
                 3               6    2245
8     0    4     6               1    2239
           5     5               9    2385
      1    3     2               7    1487
           6     6               7    2869
      2    4     3               5    2130
           5     2               5    2095
           6     3               6    2131
      4    5     0               0    1480
      13   5     4               1    2462
11    0    6     3               6    2169
      1    4     0               7    1403
      2    2     0               5    1115
           5     3               0    1940
      4    2     3               1    1900
           3     5               7    2088
12    0    2     0               0     836
      1    0     3               9    1269
           4     2               6    1824
      2    4     0               5    1457
                 5               5    2194
      4    0     3               7    1433
      8    6     3               6    2554
      13   4     3               5    2380

In [ ]:
slic = dw[(dw['apple'] == 12) | (dw['kiwi'] == 13) & (dw['bread'] == 6)]

In [ ]:
slic

,apple,kiwi,bread,cheese,dairymilk,kindercreamy,teddy,talkingtom,tomato,onion,amount
4,8,13,6,0,6,6,5,4,8,1,2462
7,12,1,2,5,0,11,4,2,5,6,1824
15,12,2,6,5,6,0,4,5,4,5,2194
17,7,13,6,5,5,8,4,3,6,6,2245
20,12,8,6,5,12,8,6,3,0,6,2554
22,12,2,9,4,7,8,4,0,7,5,1457
41,12,1,5,4,6,3,0,3,8,9,1269
46,12,0,2,5,0,3,2,0,6,0,836
48,12,4,15,5,12,3,0,3,0,7,1433
49,12,13,6,9,5,6,4,3,5,5,2380